name: 'Initialize Private Actions'
description: ''
inputs:
  token:
    required: true
    description: 'Github repository token'
  path:
    required: false
    default: actions
  repo:
    required: false
    default: cloudcoach/actions
  ref:
    required: false
    default: main
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
